"""The Shoonya Farms product catalog used to seed the database.

Prices are in whole rupees. `variants` are (label, price, mrp) tuples;
mrp (compare-at price) may be None.
"""

PRODUCTS = [
    # ------------------------------------------------------------------ Ghee
    {
        "slug": "desi-cow-ghee",
        "name": "Desi Cow Ghee",
        "category": "Ghee",
        "icon": "ghee",
        "theme": "ghee",
        "description": "Golden A2 ghee, slow-churned from cultured curd using the traditional bilona method. Nutty, aromatic and grainy — the way ghee should be.",
        "rating": 4.9,
        "reviews": 312,
        "badge": "best",
        "featured": True,
        "variants": [("200 ml", 250, None), ("500 ml", 575, 650), ("1 L", 1090, 1250)],
    },
    {
        "slug": "gir-cow-a2-ghee",
        "name": "Gir Cow A2 Ghee",
        "category": "Ghee",
        "icon": "ghee",
        "theme": "ghee",
        "description": "Pure A2 ghee from indigenous Gir cows, hand-churned in small batches. Rich in flavour and prized in Ayurveda.",
        "rating": 4.9,
        "reviews": 208,
        "badge": "best",
        "featured": True,
        "variants": [("200 ml", 399, None), ("500 ml", 975, 1100), ("1 L", 1890, 2100)],
    },
    {
        "slug": "pahadi-bilona-ghee",
        "name": "Pahadi Bilona Ghee",
        "category": "Ghee",
        "icon": "ghee",
        "theme": "ghee",
        "description": "Made from the milk of free-grazing Himalayan cows, churned the slow bilona way for a deep, earthy aroma.",
        "rating": 4.8,
        "reviews": 141,
        "badge": None,
        "featured": False,
        "variants": [("200 ml", 399, None), ("500 ml", 975, None), ("1 L", 1890, None)],
    },
    {
        "slug": "sahiwal-cow-ghee",
        "name": "Sahiwal Cow Ghee",
        "category": "Ghee",
        "icon": "ghee",
        "theme": "ghee",
        "description": "Creamy, delicately sweet ghee from Sahiwal cows raised on open pastures.",
        "rating": 4.8,
        "reviews": 97,
        "badge": "new",
        "featured": False,
        "variants": [("200 ml", 350, None), ("500 ml", 850, None), ("1 L", 1650, None)],
    },
    # ----------------------------------------------------------------- Honey
    {
        "slug": "multiflora-raw-honey",
        "name": "Multi-Flora Raw Honey",
        "category": "Honey",
        "icon": "honey",
        "theme": "honey",
        "description": "Raw, unheated and unfiltered honey gathered from wild multi-floral blooms. Crystallises naturally in winter — proof it's the real thing.",
        "rating": 4.8,
        "reviews": 276,
        "badge": "best",
        "featured": True,
        "variants": [("350 g", 299, 349)],
    },
    {
        "slug": "wild-forest-honey",
        "name": "Wild-Forest Honey",
        "category": "Honey",
        "icon": "honey",
        "theme": "honey",
        "description": "Deep, robust honey foraged by wild bees in dense forests. Single-origin and utterly untamed.",
        "rating": 4.9,
        "reviews": 154,
        "badge": "best",
        "featured": True,
        "variants": [("350 g", 499, None)],
    },
    {
        "slug": "ajwain-honey",
        "name": "Ajwain Honey",
        "category": "Honey",
        "icon": "honey",
        "theme": "honey",
        "description": "Monofloral honey from ajwain (carom) blossoms — warming, with a gentle herbal kick.",
        "rating": 4.7,
        "reviews": 88,
        "badge": None,
        "featured": False,
        "variants": [("350 g", 350, None)],
    },
    {
        "slug": "jamun-honey",
        "name": "Jamun Honey",
        "category": "Honey",
        "icon": "honey",
        "theme": "honey",
        "description": "Dark, mineral-rich honey from jamun flowers, long valued for supporting healthy sugar balance.",
        "rating": 4.8,
        "reviews": 72,
        "badge": None,
        "featured": False,
        "variants": [("350 g", 450, None)],
    },
    {
        "slug": "litchi-honey",
        "name": "Litchi Honey",
        "category": "Honey",
        "icon": "honey",
        "theme": "honey",
        "description": "Light, floral and fragrant honey from litchi orchards in bloom.",
        "rating": 4.7,
        "reviews": 64,
        "badge": None,
        "featured": False,
        "variants": [("350 g", 399, None)],
    },
    {
        "slug": "tulsi-honey",
        "name": "Tulsi Honey",
        "category": "Honey",
        "icon": "honey",
        "theme": "honey",
        "description": "Honey infused with holy basil — soothing, aromatic and a monsoon favourite.",
        "rating": 4.8,
        "reviews": 59,
        "badge": "new",
        "featured": False,
        "variants": [("350 g", 399, None)],
    },
    {
        "slug": "eucalyptus-honey",
        "name": "Eucalyptus Honey",
        "category": "Honey",
        "icon": "honey",
        "theme": "honey",
        "description": "Bold, slightly mentholated honey from eucalyptus forests.",
        "rating": 4.6,
        "reviews": 41,
        "badge": None,
        "featured": False,
        "variants": [("350 g", 399, None)],
    },
    {
        "slug": "mustard-honey",
        "name": "Mustard Honey",
        "category": "Honey",
        "icon": "honey",
        "theme": "honey",
        "description": "Smooth, quick-to-crystallise honey from vast mustard fields.",
        "rating": 4.6,
        "reviews": 38,
        "badge": None,
        "featured": False,
        "variants": [("350 g", 350, None)],
    },
    {
        "slug": "dhaniya-honey",
        "name": "Coriander (Dhaniya) Honey",
        "category": "Honey",
        "icon": "honey",
        "theme": "honey",
        "description": "Mild, spiced honey from coriander blossoms with a warm finish.",
        "rating": 4.7,
        "reviews": 45,
        "badge": None,
        "featured": False,
        "variants": [("350 g", 350, None)],
    },
    # ---------------------------------------------------- Cold-Pressed Oils
    {
        "slug": "groundnut-oil",
        "name": "Wood-Pressed Groundnut Oil",
        "category": "Cold-Pressed Oils",
        "icon": "oil",
        "theme": "oil",
        "description": "Cold-pressed in a wooden ghani from sun-dried groundnuts. Full-bodied, nutty and unrefined.",
        "rating": 4.8,
        "reviews": 132,
        "badge": "best",
        "featured": True,
        "variants": [("1 L · Glass", 450, None), ("1 L · Plastic", 420, None)],
    },
    {
        "slug": "mustard-oil",
        "name": "Wood-Pressed Mustard Oil",
        "category": "Cold-Pressed Oils",
        "icon": "oil",
        "theme": "oil",
        "description": "Pungent, alive and cold-pressed — kachi ghani mustard oil the way your grandmother used it.",
        "rating": 4.8,
        "reviews": 119,
        "badge": "best",
        "featured": False,
        "variants": [("1 L · Glass", 350, None), ("1 L · Plastic", 320, None)],
    },
    {
        "slug": "coconut-oil",
        "name": "Cold-Pressed Coconut Oil",
        "category": "Cold-Pressed Oils",
        "icon": "oil",
        "theme": "oil",
        "description": "Fresh, fragrant virgin coconut oil pressed from sun-dried copra. For cooking, hair and skin.",
        "rating": 4.7,
        "reviews": 86,
        "badge": None,
        "featured": False,
        "variants": [("100 ml", 199, None), ("500 ml", 749, 820)],
    },
    {
        "slug": "flaxseed-oil",
        "name": "Cold-Pressed Flax Seed Oil",
        "category": "Cold-Pressed Oils",
        "icon": "oil",
        "theme": "oil",
        "description": "Omega-3 rich flaxseed oil, cold-pressed to preserve every nutrient.",
        "rating": 4.6,
        "reviews": 40,
        "badge": None,
        "featured": False,
        "variants": [("100 ml", 250, None)],
    },
    {
        "slug": "kalonji-oil",
        "name": "Cold-Pressed Kalonji Oil",
        "category": "Cold-Pressed Oils",
        "icon": "oil",
        "theme": "oil",
        "description": "Potent black-seed (nigella) oil, cold-pressed and prized in traditional wellness.",
        "rating": 4.7,
        "reviews": 33,
        "badge": None,
        "featured": False,
        "variants": [("100 ml", 450, None)],
    },
    {
        "slug": "moringa-oil",
        "name": "Cold-Pressed Moringa Oil",
        "category": "Cold-Pressed Oils",
        "icon": "oil",
        "theme": "oil",
        "description": "Lightweight, antioxidant-rich moringa seed oil for cooking and skincare.",
        "rating": 4.8,
        "reviews": 28,
        "badge": "new",
        "featured": False,
        "variants": [("100 ml", 550, None)],
    },
    {
        "slug": "pumpkin-seed-oil",
        "name": "Cold-Pressed Pumpkin Seed Oil",
        "category": "Cold-Pressed Oils",
        "icon": "oil",
        "theme": "oil",
        "description": "Dark, nutty pumpkin seed oil — a gourmet finishing oil packed with zinc.",
        "rating": 4.6,
        "reviews": 22,
        "badge": None,
        "featured": False,
        "variants": [("100 ml", 450, None)],
    },
    # ------------------------------------------------------- Essential Oils
    {
        "slug": "eucalyptus-essential-oil",
        "name": "Eucalyptus Essential Oil",
        "category": "Essential Oils",
        "icon": "essential",
        "theme": "essential",
        "description": "Pure steam-distilled eucalyptus oil — clearing, fresh and invigorating for diffusers and steam.",
        "rating": 4.7,
        "reviews": 54,
        "badge": None,
        "featured": False,
        "variants": [("30 ml", 299, None)],
    },
    {
        "slug": "lemongrass-essential-oil",
        "name": "Lemongrass Essential Oil",
        "category": "Essential Oils",
        "icon": "essential",
        "theme": "essential",
        "description": "Bright, citrusy lemongrass oil for aromatherapy and natural home fragrance.",
        "rating": 4.7,
        "reviews": 49,
        "badge": None,
        "featured": False,
        "variants": [("30 ml", 299, None)],
    },
    {
        "slug": "peppermint-essential-oil",
        "name": "Peppermint Essential Oil",
        "category": "Essential Oils",
        "icon": "essential",
        "theme": "essential",
        "description": "Cool, crisp peppermint oil — reviving for the senses and the workspace.",
        "rating": 4.8,
        "reviews": 61,
        "badge": "new",
        "featured": False,
        "variants": [("30 ml", 350, None)],
    },
    # -------------------------------------------------------- Dals & Pulses
    {
        "slug": "arhar-toor-dal",
        "name": "Hand-Milled Arhar (Toor) Dal",
        "category": "Dals & Pulses",
        "icon": "dal",
        "theme": "dal",
        "description": "Unpolished, hand-milled split pigeon peas. No oil coating, no polishing — just honest dal.",
        "rating": 4.8,
        "reviews": 143,
        "badge": "best",
        "featured": True,
        "variants": [("500 g", 110, None), ("1 kg", 200, None), ("5 kg", 950, 1050)],
    },
    {
        "slug": "moong-dal",
        "name": "Hand-Milled Split Moong Dal",
        "category": "Dals & Pulses",
        "icon": "dal",
        "theme": "dal",
        "description": "Light, easy-to-digest split green gram, hand-milled and unpolished.",
        "rating": 4.7,
        "reviews": 98,
        "badge": None,
        "featured": False,
        "variants": [("500 g", 120, None), ("1 kg", 220, None)],
    },
    {
        "slug": "urad-dal",
        "name": "Hand-Milled Split Urad Dal",
        "category": "Dals & Pulses",
        "icon": "dal",
        "theme": "dal",
        "description": "Creamy split black gram for dal makhani, idli and dosa batter.",
        "rating": 4.7,
        "reviews": 76,
        "badge": None,
        "featured": False,
        "variants": [("500 g", 120, None), ("1 kg", 230, None)],
    },
    {
        "slug": "chana-dal",
        "name": "Chana Dal",
        "category": "Dals & Pulses",
        "icon": "dal",
        "theme": "dal",
        "description": "Wholesome split Bengal gram, naturally grown and unpolished.",
        "rating": 4.6,
        "reviews": 64,
        "badge": None,
        "featured": False,
        "variants": [("500 g", 90, None), ("1 kg", 170, None)],
    },
    # -------------------------------------------------------- Atta & Grains
    {
        "slug": "wheat-atta",
        "name": "Chemical-Free Wheat Atta",
        "category": "Atta & Grains",
        "icon": "atta",
        "theme": "atta",
        "description": "Stone-milled whole wheat flour from chemical-free wheat. Soft rotis, full of fibre.",
        "rating": 4.8,
        "reviews": 187,
        "badge": "best",
        "featured": True,
        "variants": [("1 kg", 80, None), ("5 kg", 350, 400)],
    },
    {
        "slug": "kathiya-wheat-atta",
        "name": "Organic Kathiya Wheat Atta",
        "category": "Atta & Grains",
        "icon": "atta",
        "theme": "atta",
        "description": "Premium hard (durum) Kathiya wheat, stone-milled for a nutty, protein-rich atta.",
        "rating": 4.8,
        "reviews": 91,
        "badge": None,
        "featured": False,
        "variants": [("1 kg", 120, None), ("5 kg", 550, None)],
    },
    {
        "slug": "sarbati-atta",
        "name": "Sarbati Wheat Atta",
        "category": "Atta & Grains",
        "icon": "atta",
        "theme": "atta",
        "description": "Sweet, soft-textured Sarbati wheat flour — a north-Indian favourite.",
        "rating": 4.6,
        "reviews": 52,
        "badge": None,
        "featured": False,
        "variants": [("1 kg", 75, None)],
    },
    {
        "slug": "kathiya-daliya",
        "name": "Kathiya Daliya (Broken Wheat)",
        "category": "Atta & Grains",
        "icon": "atta",
        "theme": "atta",
        "description": "Coarsely milled broken wheat for wholesome porridge, khichdi and upma.",
        "rating": 4.6,
        "reviews": 37,
        "badge": None,
        "featured": False,
        "variants": [("500 g", 90, None)],
    },
    {
        "slug": "kala-namak-rice",
        "name": "Kala Namak Rice",
        "category": "Atta & Grains",
        "icon": "rice",
        "theme": "atta",
        "description": "Aromatic heirloom black-salt rice from the Buddhist heartland — fragrant and nutrient-dense.",
        "rating": 4.8,
        "reviews": 44,
        "badge": "new",
        "featured": False,
        "variants": [("1 kg", 250, None)],
    },
    # ---------------------------------------------------------- Sweeteners
    {
        "slug": "jaggery",
        "name": "Jaggery (Gud)",
        "category": "Sweeteners",
        "icon": "sweet",
        "theme": "sweet",
        "description": "Chemical-free sugarcane jaggery, boiled and set the traditional way. No sulphur, no bleaching.",
        "rating": 4.8,
        "reviews": 121,
        "badge": "best",
        "featured": True,
        "variants": [("700 g", 150, None)],
    },
    {
        "slug": "jaggery-powder",
        "name": "Jaggery Powder",
        "category": "Sweeteners",
        "icon": "sweet",
        "theme": "sweet",
        "description": "Free-flowing jaggery powder — an easy, wholesome swap for refined sugar.",
        "rating": 4.8,
        "reviews": 104,
        "badge": None,
        "featured": False,
        "variants": [("500 g", 130, None), ("900 g", 230, None)],
    },
    {
        "slug": "khandsari-sugar",
        "name": "Khandsari Sugar",
        "category": "Sweeteners",
        "icon": "sweet",
        "theme": "sweet",
        "description": "Unrefined, unbleached raw sugar crystals with minerals intact.",
        "rating": 4.7,
        "reviews": 73,
        "badge": None,
        "featured": False,
        "variants": [("500 g", 110, None), ("1 kg", 200, None)],
    },
    {
        "slug": "khandsari-powder",
        "name": "Khandsari Powder",
        "category": "Sweeteners",
        "icon": "sweet",
        "theme": "sweet",
        "description": "Finely powdered khandsari for baking and beverages.",
        "rating": 4.6,
        "reviews": 48,
        "badge": None,
        "featured": False,
        "variants": [("500 g", 120, None), ("1 kg", 220, None)],
    },
    {
        "slug": "brown-sugar",
        "name": "Natural Brown Sugar",
        "category": "Sweeteners",
        "icon": "sweet",
        "theme": "sweet",
        "description": "Soft, molasses-rich brown sugar with a warm caramel note.",
        "rating": 4.6,
        "reviews": 59,
        "badge": None,
        "featured": False,
        "variants": [("500 g", 110, None), ("1 kg", 200, None)],
    },
    # ------------------------------------------------------- Spices & Salt
    {
        "slug": "lakadong-turmeric",
        "name": "Lakadong Turmeric Powder",
        "category": "Spices & Salt",
        "icon": "spice",
        "theme": "spice",
        "description": "High-curcumin Lakadong turmeric from Meghalaya — vivid, potent and stone-ground.",
        "rating": 4.9,
        "reviews": 97,
        "badge": "best",
        "featured": True,
        "variants": [("200 g", 150, None)],
    },
    {
        "slug": "himalayan-pink-salt",
        "name": "Himalayan Pink Salt",
        "category": "Spices & Salt",
        "icon": "salt",
        "theme": "salt",
        "description": "Hand-mined rock salt rich in trace minerals, with a clean, mellow taste.",
        "rating": 4.7,
        "reviews": 68,
        "badge": None,
        "featured": False,
        "variants": [("500 g", 120, None)],
    },
    # -------------------------------------------------------------- Combos
    {
        "slug": "ghee-duo-combo",
        "name": "Ghee Duo: Desi + Pahadi",
        "category": "Combos",
        "icon": "combo",
        "theme": "combo",
        "description": "A pairing of our Desi Cow and Pahadi Bilona ghee (500 ml each) — the perfect gift for a healthy kitchen.",
        "rating": 4.9,
        "reviews": 64,
        "badge": "best",
        "featured": True,
        "variants": [("500 ml × 2", 2050, 2300)],
    },
    {
        "slug": "immunity-combo",
        "name": "Immunity Combo",
        "category": "Combos",
        "icon": "combo",
        "theme": "combo",
        "description": "Jaggery powder + Multi-Flora honey + Desi ghee — a wholesome daily-wellness trio.",
        "rating": 4.8,
        "reviews": 41,
        "badge": None,
        "featured": False,
        "variants": [("3-item pack", 899, 1050)],
    },
    {
        "slug": "dal-trio-combo",
        "name": "Dal Trio: Moong + Arhar + Urad",
        "category": "Combos",
        "icon": "combo",
        "theme": "combo",
        "description": "Three hand-milled dals (1 kg each) to stock a wholesome pantry.",
        "rating": 4.7,
        "reviews": 38,
        "badge": "sale",
        "featured": False,
        "variants": [("1 kg × 3", 620, 700)],
    },
]
